baseURL: https://fljd.in

author:
  name: Florent Jardin

paginate: 5
rssLimit: 5
theme: fljdin

permalinks:
  posts: /:year/:month/:day/:slug
  pages: /:slug

related:
  includeNewer: true
  threshold: 80
  toLower: false
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 80
  - name: categories
    weight: 50
  - name: date
    weight: 10

removePathAccents: true
pygmentsUseClasses: true

# i18n
languageCode: fr
defaultContentLanguage: fr

languages:
  fr:
    title: "Carnet de découvertes"
    languageCode: fr
    languageName: Français
    contentDir: content/fr
    weight: 1
    menu: 
      navigation:
      - identifier: about
        title: "À propos"
        url: "/a-propos"
      - identifier: archives
        title: "Archives"
        url: "/archives"
  en:
    title: "Discovery notebook"
    languageCode: en
    languageName: English
    contentDir: content/en
    weight: 2
    menu:
      navigation:
      - identifier: about
        title: "About me"
        url: "/en/about"
      - identifier: archives
        title: "Archives"
        url: "/en/archives"