baseURL: https://fljd.in
title: Florent Jardin

author:
  name: Florent Jardin

paginate: 5
rssLimit: 5

permalinks:
  posts: /:year/:month/:day/:slug

disableKinds:
- taxonomy
- term

removePathAccents: true
pygmentsUseClasses: true

outputFormats:
  FEED:
    mediaType: application/rss+xml
    baseName: feed

outputs:
  home: [ HTML, FEED ]
  section: [ HTML ]