baseURL: https://fljdin.github.io
title: Florent Jardin

author:
  name: Florent Jardin

paginate: 5
rssLimit: 5

permalinks:
  posts: /:year/:month/:day/:slug

removePathAccents: true
pygmentsUseClasses: true