baseURL: https://fljd.in

author:
  name: Florent Jardin

paginate: 5
rssLimit: 5
theme: fljdin

permalinks:
  posts: /:year/:month/:day/:slug
  pages: /:slug

related:
  includeNewer: true
  threshold: 80
  toLower: false
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 80
  - name: categories
    weight: 50
  - name: date
    weight: 10

removePathAccents: true
pygmentsUseClasses: true

# i18n
defaultContentLanguage: fr
languages:
  fr:
    languageName: Français
    contentDir: content/fr
    weight: 1
    title: "Carnet de découvertes"
  en:
    languageName: English
    contentDir: content/en
    weight: 2
    title: "Discovery notebook"